version: '3.6'
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "laravel"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "dfjhdfguryt"
        ports:
            - "5432:5432"
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/app
        networks:
            default:
                aliases:
                    - ${SERVER_NAME}
                    - www.${SERVER_NAME}
        depends_on:
            - php-fpm
    redis:
        image: redis:7
        ports:
            - "63791:6379"

    php-fpm:
        build:
            context: docker/fpm
        environment:
            - "DB_HOST=postgres"
            - "DB_PORT=5432"
            - "REDIS_HOST=127.0.0.1"
            - "REDIS_PORT=6379"
        depends_on:
            - redis
            - postgres
        volumes:
            - ./:/var/www
        expose:
            - "9000"
